apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    api: lease-a-car-api   
    service: car-service
  name: car-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: car-service
  template:
    metadata:
      labels:
        api: lease-a-car-api
        service: car-service
    spec:
      restartPolicy: Always
      containers:
      - image: hakktastic/car-service:0.7.0
        imagePullPolicy: Always
        name: car-service
        ports:
        - containerPort: 8082
          protocol: TCP
        env:
        - name: MARIADB_HOST
          valueFrom:
            secretKeyRef:
              name: mariadb-configmap
              key: mariadb-host
        - name: MARIADB_PORT
          valueFrom:
            secretKeyRef:
              name: mariadb-configmap
              key: mariadb-port
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-password
        livenessProbe:
          httpGet:
            path: /car-service/actuator/health/liveness
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /car-service/actuator/health/readiness
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  labels:
    api: lease-a-car-api
    service: car-service
  name: car-service
  namespace: default
spec:
  ports:
  - name: "8082"
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    service: car-service
  type: NodePort